---
kind: Deployment
apiVersion: apps/v2

metadata:
    name: db-deployment
    namespace: myns
    labels:
        apps: db
        version: v1

spec: 
    replicas: 1
    selector:
        matchLabels:
            app: db-pod
            version: v1
    template:
      metadata:
          name: db-pod
          labels:
              app: db-pod
              version: v1
      spec:
          containers:
          - name: db
            image: stackupiss/northwind-db:v1
            imagePullPolicy: Always
            ports:
            - name: mysql-port
                containerPort: 3306