---
kind: Deployment
apiVersion: apps/v1

metadata:
    name: db-deployment
    namespace: myns
    labels:
        apps: db
        version: v1

spec: 
    replicas: 1
    selector:
        matchLabels:
            app: db-pod
            version: v1
    template:
      metadata:
          name: db-pod
          labels:
              app: db-pod
              version: v1
      spec:
          containers:
          - name: db
            image: stackupiss/northwind-db:v1
            imagePullPolicy: Always
            ports:
            - name: mysql-port
                containerPort: 3306

---
kind: Service
apiVersion: v1

metadata:
    name: db-svc
    namespace: myns
    labels:
        app: app-svc
  
spec:
    type: ClusterIP
    selector:
        app: db-pod
    ports:
    - name: db-svd-pod
      port: 3306
      targetport: mysql-port
